import { ReactNode, useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { Activity, BookOpen, ChevronRight, CircleHelp, FileCheck2, LayoutDashboard, MapPinned, Settings2, X, Zap } from "lucide-react";
import { apiGet, getApiErrorMessage, safeText } from "@/lib/api";

type Site = Record<string, any>;
type MethodologyCategory = { label: string; items: string[] };
type MethodologyNotes = { categories: MethodologyCategory[]; load_note: string };

function MethodologyOverlay({ onClose }: { onClose: () => void }) {
  const [state, setState] = useState<{ loading: boolean; error?: string; data?: MethodologyNotes }>({ loading: true });
  useEffect(() => { apiGet<MethodologyNotes>("/api/methodology").then(data => { if (!Array.isArray(data.categories)) throw new Error("The API returned invalid methodology categories."); setState({ loading: false, data }); }).catch(error => setState({ loading: false, error: getApiErrorMessage(error, "Methodology unavailable.") })); }, []);
  return <div className="overlay-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><section className="overlay" role="dialog" aria-modal="true" aria-labelledby="methodology-title"><div className="overlay-head"><div><div className="eyebrow">PROVENANCE / HOW TO READ DIYA</div><h2 id="methodology-title">Assumptions, not measurements</h2><p className="overlay-lede">DIYA separates what the site measured from what the model assumes, so every recommendation can be questioned in the field.</p></div><button className="icon-button" onClick={onClose} aria-label="Close methodology"><X size={18} /></button></div>{state.loading && <div className="designed-loading"><span className="loading-line" /><p>Reading the model notes…</p></div>}{state.error && <div className="inline-error"><CircleHelp size={16} /> {state.error}</div>}{state.data && <div className="methodology-list">{state.data.categories.map(category => <div className="methodology-item" key={category.label}><div className="eyebrow">{category.label}</div><p>{category.items.join(" ")}</p></div>)}<div className="methodology-item"><div className="eyebrow">LOAD NOTE</div><p>{safeText(state.data.load_note)}</p></div></div>}<p className="provenance"><span className="status-dot" /> Weather is real historical/live data. Economics are configurable assumptions — not utility bills.</p></section></div>;
}

export function Shell({ site, children }: { site?: Site; children: ReactNode }) {
  const [location] = useLocation(); const [methodologyOpen, setMethodologyOpen] = useState(false); const siteId = site?.site_id ?? location.split("/")[2];
  const nav = siteId ? [{ label: "Overview", group: "UNDERSTAND", href: `/site/${siteId}`, icon: LayoutDashboard }, { label: "Live Dispatch", group: "OPERATE", href: `/site/${siteId}/dispatch`, icon: Activity }, { label: "Evidence", group: "PROVE", href: `/site/${siteId}/evidence`, icon: FileCheck2 }, { label: "Manage", group: "ACCOUNT / SITE", href: `/site/${siteId}/manage`, icon: Settings2 }] : [];
  const current = nav.find(item => location === item.href || (item.href !== `/site/${siteId}` && location.startsWith(item.href)));
  return <div className="app-shell"><aside className="rail"><Link href={siteId ? `/site/${siteId}` : "/"} className="wordmark"><span>DIYA</span><small>dispatch intelligence</small></Link><div className="rail-rule" /><nav className="nav-list" aria-label="Primary navigation">{nav.map(item => { const active = location === item.href || (item.href !== `/site/${siteId}` && location.startsWith(item.href)); const Icon = item.icon; return <div className="nav-group" key={item.href}><div className="eyebrow nav-group-title">{item.group}</div><Link href={item.href} className={`nav-link ${active ? "active" : ""}`}><Icon size={16} strokeWidth={1.7} /><span>{item.label}</span></Link></div>; })}</nav><div className="rail-footer"><button className="quiet-link" onClick={() => setMethodologyOpen(true)}><BookOpen size={15} /> Methodology</button><div className="rail-footnote"><span className="status-dot pulse-dot" /> Live data connection<br /><span>Forecast-aware operations</span></div></div></aside><main className="main-column"><header className="topbar"><div className="site-context"><MapPinned size={15} /><span title={site?.display_name}>{site?.display_name ?? (siteId ? "Site detail" : "Setup")}</span>{siteId && <><span className="slash">/</span><span className="context-state"><span className="status-dot pulse-dot" /> Monitoring</span></>}</div><div className="topbar-right">{current && <span className="current-page">{current.label}</span>}{siteId && <button className="assumptions-link" onClick={() => setMethodologyOpen(true)}>Assumptions, not measurements <ChevronRight size={14} /></button>}</div></header><div className="main-content page-enter">{children}</div><footer className="page-footer"><span>DIYA · Forecast-aware microgrid operations</span><button onClick={() => setMethodologyOpen(true)}>Weather is real data · Economics are configurable assumptions</button></footer></main>{siteId && <nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(item => { const active = location === item.href || (item.href !== `/site/${siteId}` && location.startsWith(item.href)); const Icon = item.icon; return <Link key={item.href} href={item.href} className={active ? "active" : ""}><Icon size={17} /><span>{item.label === "Live Dispatch" ? "Dispatch" : item.label}</span></Link>; })}<button onClick={() => setMethodologyOpen(true)}><BookOpen size={17} /><span>Trust</span></button></nav>}{methodologyOpen && <MethodologyOverlay onClose={() => setMethodologyOpen(false)} />}</div>;
}

export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="page-header"><div><div className="header-kicker"><span className="eyebrow">{eyebrow}</span><span className="header-rule" /></div><h1>{title}</h1>{description && <p className="page-description">{description}</p>}</div>{action && <div>{action}</div>}</div>; }
export function LoadingState({ copy = "Connecting to DIYA — this can take up to a minute on first load" }: { copy?: string }) { return <div className="loading-state"><div className="loading-orbit"><span /><span /><span /></div><p>{copy}</p><small>Using live site data · no synthetic values</small></div>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="error-state"><div><div className="eyebrow">LIVE PLAN UNAVAILABLE</div><p>{message}</p></div><button className="button button-secondary" onClick={onRetry}>Try again</button></div>; }
export function EmptyState({ title, body }: { title: string; body: string }) { return <div className="empty-state"><Zap size={18} /><div><strong>{title}</strong><p>{body}</p></div></div>; }
